:doctitle: Blogger vers Asciidoctor article 2
:description: Migrer son blog de blogger vers un blog généré via Asciidoctor
:keywords: Web,Blogger,Asciidoctor,Java
:author: Guillaume EHRET - Dev-Mind
:notitle:
:revdate: 2017/04/12
:category: Java
:teaser: Je vais essayer d'expliquer pourquoi et comment j'ai choisi de changer ma manière de publier mes articles.
:imgteaser: ../../img/blog/unknown.png

Je suis rédacteur du blog http://javamind-fr.blogspot.fr[JavaMind] depuis maintenant 7 ans et initialement quand j'ai décidé de me lancer j'ai choisi une plateforme qui me laissait la souplesse que j'attendais pour la publication de mes articles. Vous trouverez dorénavant mes articles directement sur le site https://dev-mind.fr

Je vais essayer d'expliquer pourquoi et comment j'ai choisi de changer ma manière de publier mes articles.

== Remontons dans le temps

A l'époque je ne voulais pas faire comme tout le monde et me créer un environnement sous Wordpress. J'ai donc choisi blogspot qui a toujours répondu à mes attentes. Bénéficier d'une telle plateforme vous évite par exemple de gérer des problématiques techniques comme l'hébergement, le référencement, le mode draft, la disponibilité des articles sur tous les devices.

Une fois que vous vous êtes lancés dans une routine c'est un peu comme si vous vous enfermez dans une prison. A chaque nouvel article, vous vous dites que vous ferez ça bientôt. Pour ma part plusieurs années se sont écoulées avant d'agir.

== Pourquoi écrire un blog ?

Avant d'engager une migration, je me suis déjà posé la question :  "Mais pourquoi tu écris ? Ca ne te rapporte rien... ". Et c'est plutôt vrai.

pouvez mieux faire mais personnellement j'ai toujours remis ça aux calendes grecques. Pour être aussi franc j'attendais vraiment de trouver une solution simple à mon problème. Trouve

== Une formidable aventure


++++
<p><span id="replaceMe">Sample content</span> replaced by Javascript</p>
<script>
document.getElementById('replaceMe').innerHTML = 'New content!'
</script>
++++

[source, javascript, subs="none"]
----
function sayHello(delay) {
  // delay defaults to 5 seconds
  delay = delay || 5
  setTimeout(() => console.log('Hello World!'), delay * 1000)
}

sayHello(2) // => 2 seconds later: "Hello World!"
sayHello()  // => 5 seconds later: "Hello World!"
----

== My First Experience with the Dangers of Documentation


== Hello world

Ceci est un *exemple*
