:doctitle: Workbox la toolbox pour les progressive webapps
:description:  Comment utiliser Workbox la nouvelle toolbox de Google faite pour faciiter la création de vos progressive webapps
:keywords: Web, PWA, ServiceWorker, Workbox
:author: Guillaume EHRET - Dev-Mind
:revdate: 2017-07-02
:category: Web
:teaser: Notre voyage pour mieux connaître les services workers s'achève avec la présentation de la nouvelle toolbox présentée à Google IO/2017, Workbox et Lighthouse
:status: draft

Après avoir présenter ce qu'https://www.dev-mind.fr/blog/2017/service_worker.html[était un service worker] et comment https://www.dev-mind.fr/blog/2017/creer_service_worker.html[en ajouter un dans votre application], nous allons aujourd'hui nous attarder sur la nouvelle toolbox https://workboxjs.org/[Workbox] présentée à Google IO/2017.

== Pourquoi un nouveau projet ?

On peut se poser la question de pourquoi Google met en place un nouveau projet alors que des solutions comme https://github.com/GoogleChrome/sw-precache[sw-precache] et https://github.com/GoogleChrome/sw-toolbox[sw-toolbox] existent (voir https://www.dev-mind.fr/blog/2017/creer_service_worker.html[mon dernier article] sur le sujet). En fait il y a eu pas mal de modifications dans le code depuis la mise en place de ces solutions et https://github.com/GoogleChrome/sw-toolbox[sw-toolbox] n'adresse pour le moment qu'une partie de ce que vous pouvez faire avec des services workers (exclusivement du cache de ressources). Il fallait donc revoir pas mal de choses et comme beaucoup de personnes utilisent déjà ce projet il était difficile de faire de gros changement sans mettre en péril la compatibilité ascendante.

https://workboxjs.org/[Workbox] a été pensé modulaire et vous pouvez faire votre marché pour n'utilisez que les éléments dont vous avez besoin. Quand vous voulez créer des sites performants il est important de n'embarquer que les ressources vraiment nécéssaire pour limiter un maximum la taille de votre site.


== Qu'est ce que Workbox ?

https://workboxjs.org/[Workbox] a été créé pour vous faciliter la mise en place sur votre site ou votre application, de nombreuses fonctionnalités construites sur les services workers. Le but est de vous fournir un maximum d'outil pour transformer votre application en https://www.dev-mind.fr/blog/2017/service_worker.html[progressive webapp]. https://workboxjs.org/[Workbox] permet de générer les fichiers de configuration et de vous appuyer sur des scénarios éprouvés.

Utiliser les services workers est assez sensible au niveau sécurité et au niveau de la gestion du cache des ressources. Il est à mon sens important d'utiliser une librairie externe qui évolue sans cesse et où les bug fix sont résolus rapidement.

Comme je le disais plus haut https://workboxjs.org/[Workbox] a vraiment été pensé de manière modulaire. C'est un peu comme un magasin dans lequel vous allez pouvoir faire votre marcher parmi plusieurs librairies ou outils faiblement couplés les uns avec les autres.


Vous avez une multitude de petites librairies bas niveau

=== https://workboxjs.org/reference-docs/latest/module-workbox-build.html[workbox-build]
https://workboxjs.org/reference-docs/latest/module-workbox-build.html[workbox-build] permet de générer un fichier manifeste et votre service worker. Ce module node s'intègre facilement à votre processus de build Gulp ou Webpack ou autre...

Le but est de générer la liste des ressources qui peuvent être "précachée" par un service worker. Un hash est associé à chacune des ressources afin de pouvoir mettre à jour intelligemment le cache et de supprimer les ressources qui ne seraient plus à jour. En détail cette librairie permet de

* générer un service worker avec la liste des ressources à mettre dans le cache
* générer un fichier manifest pour ensuite l'injecter dans votre application pour pouvoir accéder aux URL et au détail des modificatons des ressources
* injecter un fichier manifest dans un service worker existant. Vous controlez l'écriture de votre service worker tout en bénéficiant du précaching automatique

Un exemple

=== https://workboxjs.org/reference-docs/latest/module-workbox-cache-expiration.html#workbox-cache-expiration[workbox-cache-expiration]

Quand vous utilisez des services workers ou plus généralement du cache de ressources dans le navigateur web vous avez toujours la hantise que votre cache soit mal configuré et que les ressources ne soient jamais mise à jour.

workbox-runtime-caching—Implements various runtime caching strategies.

workbox-cache-expiration—Expires cached responses based on age or a maximum number of entries.

Workbox also includes modules for other common service worker use-cases:

workbox-google-analytics—Stores and retries offline Google Analytics requests when a connection is available.

workbox-background-sync—Queues failed requests and uses the Background Sync API to replay those requests when the user comes back online.



Workbox is a collection of loosely-coupled libraries and tools, that focus on different service worker features and use-cases. The two core tools that Workbox provides are:

workbox-sw—A service worker library that makes fetch requests and caching as easy as possible.

workbox-cli—A command-line tool that generates a service worker and a file manifest, which then makes use of the workbox-sw module to become a fully-functioning service worker.

These two high-level tools are built up from a number of lower-level modules that can be used independently or mixed-and-matched:

workbox-build—Generates a file manifest or service worker, that can then be used with workbox-sw. The workbox-build module makes it easy to generate a service working using Gulp, Webpack, or any other build tool you might use.

workbox-runtime-caching—Implements various runtime caching strategies.

workbox-cache-expiration—Expires cached responses based on age or a maximum number of entries.

Workbox also includes modules for other common service worker use-cases:

workbox-google-analytics—Stores and retries offline Google Analytics requests when a connection is available.

workbox-background-sync—Queues failed requests and uses the Background Sync API to replay those requests when the user comes back online.

Workbox is a rethink our previous service worker libraries and tools, sw-toolbox and sw-precache, and is designed to be more modular, flexible, and extensible.

You're sold on the advantages of adding a service worker to your web app—swapping the uncertainty of the network for the promise of a fast, offline- first, service worker-powered experience. But to write your own service worker from scratch, you have to clear some hurdles:

Precaching URLs easily and reliably.
Incrementing a cache version string to ensure that precached resources are updated.
Implementing a cache expiration strategy to account for cache size or entry age.
Building common patterns such as lie-fi network timeouts and boilerplate code.
Capturing and reporting Google analytics data during offline usage.
You can address all of these drawbacks using Workbox.


== Utiliser Workboxjs et vérifier le fonctionnement

C'est ce que nous verrons dans le prochain article sur les services workers
